### ISSUE TITLE
Builder function

### ISSUE THREAD

**Issue by jrgmartin** [bigspring/monolith#163]
A function that will allow data from any WP loop to be laid out in a variety of standard layouts. This'll help avoid repetition of code, save time and keep layouts consistent.

The function should allow us to call `get_template_part` and pass in some parameters.  These parameters will be used to dictate the layout within that file (eg. number of columns). Where the site requirement cannot fit into one of the standard layouts below, you can always create custom layouts inline.

In addition, it should be possible to either directly edit the layout files, or create overrides on a theme basis.
#### Task List:
- [x] List
- [x] Grid
- [x] ~~Tabs~~ now on #200
- [x] ~~Accordion~~ now on #200
- [x] Snippets
- [x] Panels
- [ ] ~~Gallery~~ now on #182, but this isn't a builder function, it's a shortcode

---
## Prototype function
- get_builder_part($part, $params, $wp_query_object = null)
- if $wp_query_object is null then use the default wordpress loop
- ensure we have default $params for each layout
## List
- List style (ordered, unordered, unstyled, inline, default to list)
## Grid

Arrange content within a grid
- What fields should be shown (eg. title, excerpt, image)
## Tabs
- Type (horizontal, vertical)
## Accordions
- No parameters at present
## Snippets

Small piece of markup with (for example) an image on the left and content on the right, or an image on the top and text below.
- Type (TBC stacked, horizonal)
## Panels

TBC
## Gallery

Different concept to the standard Wordpress gallery.  This would be used (for example) as a way of showing all products contained within a product CPT.
- Fields
## Modals

TBC
