### ISSUE TITLE
Restructure docs

### ISSUE THREAD

**Issue by juliotaylor** [bigspring/monolith#76]
We need to restructure and update the docs, they are wack and confusing. Things that we need to do:
- [ ] Split shortcodes and functions into their own page
- [ ] Update docs homepage so each subpage is linked (can we automate this?)
- [ ] Update child pages area to reflect new layouts
- [ ] Update links to BS3 docs
- [ ] Update [parts](https://github.com/bigspring/Monolith/wiki/Parts)
