### ISSUE TITLE
Implement optional kitchen sink

### ISSUE THREAD

**Issue by juliotaylor** [bigspring/monolith#79]
We should implement an optional "kitchen sink", a page that has every bootstrap component listed on it so we can easily test and modify components.

There's an example of one [here](http://www.oxox.co.uk/proto/bootstrap2/kitchensink.html), but this example is for BS2. I suggest we take this as a starter and update it to BS3 (also including any new components missing).

As an addon we should make this page optional, so it only shows up when we're in dev mode.
### stuff to do
- [ ] add Kitchen sink file to the theme as PHP file (kitchen-sink.php) (SM)
- [ ] on theme activation, add htaccess rule that rewrites path to file as /root/kitchen-sink (JM)
- [ ] if production mode is enabled / developed redirect to home when site is live (JM)
