### ISSUE TITLE
Create demo site

### ISSUE THREAD

**Issue by juliotaylor** [bigspring/monolith#82]
We should create a demo site for Monolith, showing different types of pages it can handle by default. 

Here's a list to get us started but needs work
- [ ] Child pages: list
- [ ] Child pages: thumbnails
- [ ] Child pages: tabs
- [ ] Child pages: accordions
- [ ] Child pages: blog
